[RADAR]
ENABLED = 1

[TRIGGER_BOT]
ENABLED = 1

[BHOP]
ENABLED = 1

[ESP]
ENABLED = 1
ENEMY_COLOR = [ 255, 0, 0,]
OPACITY = 100

[FLASH]
ENABLED = 1
VALUE = 90.58823529411765

[FOV]
ENABLED = 1
VALUE = 15.294117647058824
