[RADAR]
ENABLED = 1

[TRIGGER_BOT]
ENABLED = 1

[BHOP]
ENABLED = 1

[ESP]
ENABLED = 1
TEAM = 1
TEAM_COLOR = [ 0, 255, 25,]
ENEMY = 1
ENEMY_COLOR = [ 20, 67, 235,]

[FLASH]
ENABLED = 0
VALUE = 30

[FOV]
ENABLED = 0
VALUE = 62
